### ISSUE TITLE
Cannot build gradle project

### ISSUE THREAD

**Issue by SOF3** [lamba92/kotlin-extlib#7]
I cloned it and got this error when refreshing project:

```
Cannot get non-null property 'sonatypeUsername' on root project 'kotlin-extlib' as it does not exist
```

**Comment by SOF3** [comment]
It works when I add them in gradle.properties, but creating local.properties doesn't work

**Comment by altavir** [comment]
It is a known problem. I usually store password configuration in a separate file, not in `properties` then include it only if it exists. like this:
```kotlin
if (file("artifactory.gradle").exists()) {
    apply(from = "artifactory.gradle")
}
```

**Comment by lamba92** [comment]
I've modified the Gradle script so that it will search for publish informations in the shell enviroment, `local.properties` and `gradle.properties` in either project root or Gradle home. If noone available all the publishing related configurations will be skipped.
